export const dict_translate = {
    delete: '删除',
    done: '完成',
    mutant: '突变',
    data: '数据',
    copy: '复制',
    cancel: '取消',
    multiple_affirm: '多项审核',
    single_affirm: '单项审核',
    adjust_items: '增减条目',
    submit: '提交',
    modify: '修改',
    free_unmodified: '未审核未修改数据',
    check: '确认审核',
    sample_type: '样本类型',
    change: '更改',
    immune_connect: '免疫关联',
    add: '添加',
    false_positive: '假阳性',
    selectedSamples_check_affirm: '选中样本的无修改审核',
    delete_affirm: '删除后审核',
    check_affirm: '确认审核',
}


